### ISSUE TITLE
Show the entire trace from the start

### ISSUE THREAD

**Issue by tahini** [lttng/lttng-scope#76]
Scope waits for the trace to be analyzed before showing anything, so it might show the full trace data. The first 100ms are often the less interesting data: it has unknown state, may be incomplete (in snapshots for instance). The first thing a user would do is zoom out and try to find out where to zoom in next. So if zoomed out from the start, it avoids one extra click (and data fetch).

**Comment by alexmonthy** [comment]
I agree the first 100 ms are usually quite useless. On the other hand, if we show the full range initially, the first action to do is "zoom-in" instead of "zoom-out", because the full-range is just as useless ;)

What I do like about this idea though is that this is exactly what this type of tool is about: starting from a sea of information and digging down to interesting parts. So perhaps having "zoom-in" be the first expected action would fit more naturally.

**Comment by tahini** [comment]
With the first 100ms, you have no choice but to zoom out. No need for the user to do that :p

But with full range, you have the choice of _where_ to zoom in, so the user is involved from the start and it is less confusing for first-timers I think...
